name: GH CLI Info

on:
  push:

permissions:
  actions: read
  contents: read
  issues: read

jobs:
  gh-info:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GH CLI - Environment
        run: env

      - name: GH CLI - Version
        run: gh --version

      - name: GH CLI - Auth Status
        run: gh auth status
        continue-on-error: true

      - name: GH CLI - Repo List
        run: gh repo list ${{ github.repository_owner }} --limit 20
        continue-on-error: true

      - name: GH CLI - Issue List
        run: gh issue list --repo ${{ github.repository }}
        continue-on-error: true

      - name: GH CLI - Workflow List
        run: gh workflow list --repo ${{ github.repository }}
        continue-on-error: true
